name: CI Pipeline

on:
  push:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r ./requirements.txt
          
      - name: Run Tests
        run: |
          python -m unittest discover -s . -p "test*.py"

  build_and_push:
    runs-on: ubuntu-latest
    needs: test  

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/app:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/app:${{ github.sha }}

      - name: Tag Image as Latest
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/app:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/app:latest
