name: CI Pipeline

on:
  push:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          pip install -r ./requirements.txt
          
      # Step 4: Run Tests
      - name: Run Tests
        run: |
          python -m unittest discover -s . -p "test*.py"

  build_and_push:
    runs-on: ubuntu-latest
    needs: test  # Ensures the test job is completed successfully before this job starts

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ github.sha }}

      # Step 4: Tag Image as Latest
      - name: Tag Image as Latest
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/flask-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:latest
